version: '3'
services:
  web:
    build: ./server
    ports:
     - 3000:3000
    volumes:
     - .:/code
  mysql:
    build: ./sql
    image: "mysql-hapi"
    container_name: "mysql"
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=example

    