version: '3'
services:
    mysql:
        build:
            context: ./mysql
        ports:
            - "3306:3306"
        volumes:
            - my-datavolume:/var/lib/mysql
    node:
        build:
            context: ./node
        ports:
            - "3000:3000"
volumes:
    my-datavolume:
